[dev]
  framework = "vite"
  command = "vite"
  targetPort = 5173

[functions]
  node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https: wss:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; img-src 'self' https: data:; media-src 'self'; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http: https:; frame-src 'self' http: https:; style-src 'self' 'unsafe-inline'; font-src 'self' https: data:"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
