export const exampleAttestorSelectTableItems = [
  {
    hash: 'DLC-Link Attestor 1',
    time: '8 hours ago',
    action: 'Update Vote State',
    programs: 'TS',
    value: '0.8059 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '1 hours ago',
    action: 'Create Proposal',
    programs: 'VP',
    value: '0.8415 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '11 hours ago',
    action: 'Execute Transaction',
    programs: 'DL',
    value: '0.5634 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '13 hours ago',
    action: 'Create Proposal',
    programs: 'DL2',
    value: '0.6588 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '3 hours ago',
    action: 'Update Vote State',
    programs: 'VP',
    value: '0.4762 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '18 hours ago',
    action: 'Create Proposal',
    programs: 'TS',
    value: '0.1499 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '7 hours ago',
    action: 'Update Vote State',
    programs: 'DL2',
    value: '0.5255 iBTC',
    token: 'N/A',
  },
  {
    hash: 'DLC-Link Attestor 1',
    time: '6 hours ago',
    action: 'Create Proposal',
    programs: 'TS',
    value: '0.9675 iBTC',
    token: 'N/A',
  },
];
